### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Onekki** [readdle/swift-android-toolchain#39]

**Comment by luckyclan** [comment]
It is alive. For example there are commits in swift-java-coder or swift-java-codegen from October 2021. 
swift-android-toolchain itself doesn't have to be updated too often, because it mainly contains build scripts for all tools from other repositories (swift-java-coder, swift-java-codegen etc).
Just remember to build toolchain from the sources, because prebuilt releases are often a bit outdated.

**Comment by andriydruk** [comment]
Hi

Yes, this project is alive. There is nothing that happens because we update it only when a new version of Swift comes.
We updated the toolchain to Swift 5.4 in August. Then Apple released Swift 5.5 in September. 

The current roadmap is to release a few versions with updated dependencies for Swift 5.4 (OpenSSL/cURL) and then we are going to start work on Swift 5.5.

I'm closing this PR. If you have any questions/suggestions feel free to open a new one.
