### ISSUE TITLE
Swift tool chain 5.9 support

### ISSUE THREAD

**Issue by EddieMeng** [readdle/swift-android-toolchain#60]
Hello, I really appreciate this swift tool chain created by you guys. It is such a good technical design with lots of benefit. I'am delighted to see that this project is continuously evolving. May I know when will we have next release version supporting Swift 5.9? @andriydruk 
Thank you very much for your help。

Currently, the swift-android-toolchain 5.7 has below error when running with swift tool chain 5.9:
'swift': missingKey("product_type")

My macbook environement:

- [ MacOS Sonoma 14.1]

- [ Xcode Version] Version 15.2

- [ Macbook Pro with Apple M3 chip]

- [ Swift version]:
swift --version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by andriydruk** [comment]
Hi Eddie, 

We have a plan to start working on Swift 5.9 in the nearest feature. Unfortunately, we don't have a dedicated team that works on this project permanently. That's why we switched back and forth from our day-to-day Spark development.

Currently all our team members are on macOS Ventura with Xcode 14 and Swift 5.7
The current version of the toolchain doesn't work on Sonoma (thanks to Apple for breaking support of the previous version of Swift every year 👏)

**Comment by EddieMeng** [comment]
Hi andriydruk @andriydruk I'm very excited to hear that you guys are working on Swift 5.9 support. I really appreciate the effort you're putting into this project and am looking forward to the next release version.

**Comment by ximlu** [comment]
@andriydruk How is the progress of support for the Swift toolchain 5.9 or 5.10 going?

**Comment by elkasvirElka** [comment]
@EddieMeng Hello, do you have any estimated release date for 5.9?

**Comment by ximlu** [comment]
@elkasvirElka You seem to have @ the wrong person, but now it's already Swift6, so it's probably difficult to support it. Although their company is also using it, it feels like supporting Swift6 is far away.
